apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - tts.yaml
  - postgres.yaml
  - postgres-pvc.yaml
  - tts-pvc.yaml
  - httproute.yaml

images:
  - name: ghcr.io/jspaulsen/tts
    newTag: main
