apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - herald.yaml
  - postgres.yaml
  - postgres-pvc.yaml

images:
  - name: ghcr.io/jspaulsen/herald
    newTag: sha-cac026acc92d3e7cb86923e531c275dc5db7294b
