apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - herald.yaml
  - postgres.yaml
  - postgres-pvc.yaml
images:
  - name: ghcr.io/jspaulsen/herald
    newTag: sha-4651ba2ff2724973167a05adf1910849ef08b41f
    newName: ghcr.io/jspaulsen/herald
