apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - herald.yaml
  - postgres.yaml
  - postgres-pvc.yaml
images:
  - name: ghcr.io/jspaulsen/herald
    newTag: sha-69b89c92550625862e320ac9e3c29635c8c6d644
    newName: ghcr.io/jspaulsen/herald
