apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-route
  namespace: argocd
spec:
  parentRefs:
  - name: cloudflare-tunnel
    namespace: default
  hostnames:
  - gitops.yeebs.dev
  rules:
  - backendRefs:
    - name: argocd-server
      port: 80
