apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: herald
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: herald=ghcr.io/jspaulsen/herald
    argocd-image-updater.argoproj.io/herald.update-strategy: newest-build
    argocd-image-updater.argoproj.io/herald.allow-tags: regexp:^sha-[0-9a-f]+$
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-ssh
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/git-repository: git@github.com:jspaulsen/k8s-infra.git
spec:
  project: default
  source:
    repoURL: https://github.com/jspaulsen/k8s-infra.git
    path: applications/herald
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: herald
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
