apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: herald
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jspaulsen/k8s-infra.git
    path: applications/herald
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: herald
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
