apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jspaulsen/k8s-infra.git
    path: applications/tts
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: tts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
